// Generated by ts-to-zod
import { z } from "zod";

export const articleLockReqSchema = z.object({
  refresh: z.boolean().optional(),
});

export const articleLockResSchema = z.object({
  isLocked: z.boolean(),
  lockedByLogin: z.string(),
  lockedByName: z.string(),
  lockedByAvatarUrl: z.string(),
  lockedAt: z.number(),
  version: z.number(),
  authorLogin: z.string(),
  authorName: z.string(),
  currentUserLogin: z.string(),
  canEdit: z.boolean(),
  canLock: z.boolean(),
  canUnlock: z.boolean(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("author"),
    z.literal("lockedBy"),
    z.literal("authorOrLockedBy"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  allowChildArticles: z.boolean(),
});

export const articleSettingsReqSchema = z.object({
  projectId: z.string(),
});

export const articleSettingsResSchema = z.object({
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("author"),
    z.literal("lockedBy"),
    z.literal("authorOrLockedBy"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  allowChildArticles: z.boolean(),
});

export const issueLockReqSchema = z.object({
  refresh: z.boolean().optional(),
});

export const issueLockResSchema = z.object({
  isResolved: z.boolean(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("resolver"),
    z.literal("reporterOrResolver"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  reporterLogin: z.string(),
  reporterName: z.string(),
  resolverLogin: z.string(),
  resolverName: z.string(),
  resolvedAt: z.number(),
  currentUserLogin: z.string(),
  canReopen: z.boolean(),
});

export const issueSettingsReqSchema = z.object({
  projectId: z.string(),
});

export const issueSettingsResSchema = z.object({
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("resolver"),
    z.literal("reporterOrResolver"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

export const saveArticleSettingsReqSchema = z.object({
  projectId: z.string(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("author"),
    z.literal("lockedBy"),
    z.literal("authorOrLockedBy"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  allowChildArticles: z.boolean(),
});

export const saveArticleSettingsResSchema = z.object({
  ok: z.boolean(),
  errors: z.array(z.string()),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("author"),
    z.literal("lockedBy"),
    z.literal("authorOrLockedBy"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  allowChildArticles: z.boolean(),
});

export const saveIssueSettingsReqSchema = z.object({
  projectId: z.string(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("resolver"),
    z.literal("reporterOrResolver"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

export const saveIssueSettingsResSchema = z.object({
  ok: z.boolean(),
  errors: z.array(z.string()),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("resolver"),
    z.literal("reporterOrResolver"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

export const setArticleLockReqSchema = z.object({
  locked: z.boolean(),
});

export const setArticleLockResSchema = z.object({
  ok: z.boolean(),
  message: z.string(),
  isLocked: z.boolean(),
  lockedByLogin: z.string(),
  lockedByName: z.string(),
  lockedByAvatarUrl: z.string(),
  lockedAt: z.number(),
  version: z.number(),
  authorLogin: z.string(),
  authorName: z.string(),
  currentUserLogin: z.string(),
  canEdit: z.boolean(),
  canLock: z.boolean(),
  canUnlock: z.boolean(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("author"),
    z.literal("lockedBy"),
    z.literal("authorOrLockedBy"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
  allowChildArticles: z.boolean(),
});

// Nested schema object for validation system
export const schema = {
  article: {
    lock: {
      GET: {
        Req: articleLockReqSchema,
        Res: articleLockResSchema
      },
      POST: {
        Req: setArticleLockReqSchema,
        Res: setArticleLockResSchema
      }
    }
  },
  issue: {
    lock: {
      GET: {
        Req: issueLockReqSchema,
        Res: issueLockResSchema
      }
    }
  },
  project: {
    articleSettings: {
      GET: {
        Req: articleSettingsReqSchema,
        Res: articleSettingsResSchema
      },
      POST: {
        Req: saveArticleSettingsReqSchema,
        Res: saveArticleSettingsResSchema
      }
    },
    issueSettings: {
      GET: {
        Req: issueSettingsReqSchema,
        Res: issueSettingsResSchema
      },
      POST: {
        Req: saveIssueSettingsReqSchema,
        Res: saveIssueSettingsResSchema
      }
    }
  }
};
