// Generated by ts-to-zod
import { z } from "zod";

export const projectSettingsReqSchema = z.object({
  projectId: z.string(),
});

export const projectSettingsResSchema = z.object({
  version: z.number(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

export const saveSettingsReqSchema = z.object({
  projectId: z.string(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

export const saveSettingsResSchema = z.object({
  ok: z.boolean(),
  errors: z.array(z.string()),
  version: z.number(),
  enabled: z.boolean(),
  unlockRestriction: z.union([
    z.literal("anyone"),
    z.literal("reporter"),
    z.literal("projectAdmins"),
  ]),
  allowComments: z.boolean(),
  allowLinks: z.boolean(),
  allowWorkItems: z.boolean(),
  allowAttachments: z.boolean(),
  allowTags: z.boolean(),
});

// Nested schema object for validation system
export const schema = {
  project: {
    settings: {
      GET: {
        Req: projectSettingsReqSchema,
        Res: projectSettingsResSchema
      },
      POST: {
        Req: saveSettingsReqSchema,
        Res: saveSettingsResSchema
      }
    }
  }
};
